#!/usr/bin/env php
<?php

require_once dirname(__DIR__)."/init.php";


exit(\net\dryuf\process\command\ExternalCommandRunner::createFromClassPath()->runNew('net\dryuf\security\command\CreateUserCommand', array_slice($argv, 1)));


?>
